services:
  db: 
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fatec_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_fatec
      MYSQL_PASSWORD: password_fatec
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: SEU_USUARIO/wordpress-fatec:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8031:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user_fatec
      WORDPRESS_DB_PASSWORD: password_fatec
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8031');
        define('WP_SITEURL', 'http://localhost:8031');

volumes:
  db_data: 
