name: CI Pipeline - IEC App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verificar vulnerabilidades (Backend)
        run: |
          cd backend
          npm install
          npm audit --audit-level=high

  quality:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Instalar dependencias e rodar Lint
        run: |
          cd backend
          npm install
          npm run lint
      - name: Analise com SonarCloud 
        uses: SonarSource/sonarcloud-github-action@v2 
        with: 
          args: > 
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=.
            -Dsonar.verbose=true
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push API
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/vini-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USER }}/vini-backend:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
      - name: Subir Banco de Dados Temporario
        run: |
          docker compose up -d db
          sleep 20
      - name: Rodar Testes (Backend)
        run: |
          cd backend
          npm install
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
      
      - name: Copiar arquivo docker-compose para o servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/iec_app_teste"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/iec_app_teste
            export DOCKER_USER=${{ secrets.DOCKER_USER }}
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f