name: CI/CD WordPress Simplificado

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push
        run: |
          docker compose build
          docker compose push
        working-directory: ./wordpress

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "iec_app_teste" ]; then
              git clone https://github.com/${{ github.repository }} iec_app_teste
            fi
            cd iec_app_teste
            git pull origin main
            cd wordpress
            docker compose pull
            docker compose up -d
